### ISSUE TITLE
Raspberry Pi Digital Signage Management

### ISSUE THREAD

**Issue by bcdevex** [bcgov/queue-management#158]
<p>This issue has been auto-generated to facilitate questions about <a href="https://bcdevexchange.org/opportunities/cwu/opp-raspberry-pi-digital-signage-management">a paid opportunity</a> that has just been posted on the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-raspberry-pi-digital-signage-management">visit the opportunity page</a>. The opportunity closes on <b>Thursday, January 24, 2019</b>.</p>

**Comment by gil0109** [comment]
Hi folks, I am the lead opportunity contact for this issue. Please post any questions you have here and we'll do our best to respond promptly.

**Comment by mitfik** [comment]
I think there is a bug with the dates I guess you meant Feb as a start date, right?

> We plan to assign this opportunity by January 25th 2019 with work to start on January 11th 2019.

**Comment by gil0109** [comment]
@mitfik Yes, please note that we would propose the Start Date be January 29th, 2019.

**Comment by gil0109** [comment]
@countable Thank you for your questions.  

1. WiFi Reliability - Yes, we would want the system to retry to reconnect if there is a network issue and/or if the display (depending on your solution) stops playing due to a crash and or an update to the digital signage video.  It also includes recovering from a network glitch while downloading patches or updates. 
 The scope is limited to general connection issues not placement/signal strength, etc.

2. We use the following time zones.  Depending on the solution, this will need to be taken into account to display the correct date/time.

America/Vancouver 
America/Edmonton 
America/Dawson_Creek 

Currently we pass this to the server to display the correct timezone: https://<servername>/smartboard/999?tz=America%2FDawson_Creek

3. The current signage depending on the type of office displays either 2, 3, or 4 components.

**All offices** will display:
- An MP4 video for the main part
- Top area displays the Date & Time
**Reception offices** ALSO displays:
- The number of people that are currently waiting
**Call by Number offices** ALSO displays:
- The number of people that are currently waiting
- The Ticket number of a person that is being served

Depending on your solution, you may need to update the Vue.Js that displays the current digital signage.  This would be to get the number of people and ticket number based on the office. You could get that using Vue.JS or other method depending on your solution.  I hope that makes sense.

The three different displays that are required are located in the Appendix section of the document link provided in the Opportunity.  

https://github.com/bcgov/queue-management/blob/master/documentation/DigitalSignage/Setup%20Instructions%20for%20Raspberry%20Pi%20Kiosk.docx


Again, thank you for your enquiry.  Please let me know if you need additional clarification.

Regards,
Karim

**Comment by countable** [comment]
This makes sense, thank you!

**Comment by adamelliot** [comment]
@gil0109 Another question about the connectivity.

For connecting to WiFi is the intent that all deployed systems will use the same wireless configuration? If not how do you plan for individual maintenance? Would want images built for each location and would you need tools to manage those images?

Also, I believe "Increase the memory for the GPI" should be "Increase the memory for the GPU" is that true?

Thanks,
Adam

**Comment by adamelliot** [comment]
Thanks for your quick reply!

**Comment by adamelliot** [comment]
@gil0109 A few more questions.

1. Is the network environment for installation closed or open to the Internet?
2. Mender requires signing certificates, for the web admin portion is self signing sufficient or would you want them signed by an authority, and do you have certificates and a domain in mind, or would setting all this up be part of this project?
3. Is the OpenShift environment OpenShift Online, or is it On-Premise (IE Hosted on BC hardware in-house?

Thanks,
Adam

**Comment by gil0109** [comment]
@adamelliot Thank you for your questions.

1.  The network is currently open but the plan is to close it to only the internal network of OpenShift and the locations where the devices live.  There is an option to open portions of the internet (outbound only) if needed but not recommended.
2. Self signing is sufficient for our needs at this time.  In the future, based on Government policy we may change the certificates to trusted authorities (Entrust) but that can be done after and out of scope for this project.
3. The openshift environment is on premise with in house hardware.

Regards,
Karim

**Comment by adamelliot** [comment]
That all make sense, thanks!

**Comment by gil0109** [comment]
I want to thank everyone who submitted their proposals.  I appreciate your time and effort in providing your proposals. For the unsuccessful candidates, if you wish to have feedback, please don't hesitate to contact me.

**Comment by gil0109** [comment]
Closed with the following Pull Request: Mender Integration for RPI (client) and OpenShift (server) #184.

Great work team!!
